### PR TITLE
other sites support

### PR DESCRIPTION
**Pull request by binarygeek119**
i took the .py files for every site in the source code for youtube-dl run it thought an url extractor and did some editing to fit in the code from my limited testing it seems to work but i cant test every site but is working for me so far

### CODE REVIEW

**Comment by Rpsl** [comment]
thx for you time, i see couple problems in this PR:
1) As you write above, you can't check the functionality of these sites, neither can I. youtube-dl has maintainers who monitor this, we don't have them. I don't want to add all sites in a row, let's stick to the principle of minimum sufficiency. I propose to roll back the last PR and leave those sites whose performance you have checked
2) You make couple changes in whitespaces. If you want to have use special codestandart please add some codeformater rules like [.editorconfig](https://editorconfig.org/) or [.eslintrc](https://standardjs.com/) or [jsconfig.json](https://code.visualstudio.com/docs/languages/javascript) ... I would not want everyone who will do PR to move whitespaces

thx

**Comment by binarygeek119** [comment]
all the site listed now have been checked.
as for whitespaces i think i took care of them please let me know

**Comment by Rpsl** [comment]
@binarygeek119 thx for your time. I see it and have not forgotten it. I think it is LGFM. I will try to merge PR and publish updates before the end of this week.

jfyi

**Comment by Rpsl** [comment]
Also i think about rewrite mechanism for additional sites and move this into extension sections. I'm not sure i will do that but it may more flexible for some kind of users.

Something like that
screenshot-2021-09-14-14-21-52-b5bd5ef332

What do you think about this idea?

**Comment by binarygeek119** [comment]
I think that be great

**Pull request merged**
